controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

homepage:
  path: /
  controller: App\Controller\HomePageController::index

signin:
  path: /signin
  controller: App\Controller\SignInController::index

signup:
  path: /signup
  controller: App\Controller\SignUpController::index

create_project:
  path: /create-project
  controller: App\Controller\CreateProjectController::index

all_projects:
  path: /all-projects
  controller: App\Controller\AllProjectsController::index

project_details:
  path: /project-details/{id}
  controller: App\Controller\ProjectDetailsController::index

create_equipment:
  path: /create-equipment
  controller: App\Controller\CreateEquipmentController::index

project_list:
    path: /projects
    controller: App\Controller\ProjectController::listProjects
    
add_publication:
    path: /add-publication
    controller: App\Controller\AddPublicationController::index
    methods: ['GET', 'POST']
